// 分类仅作维护元数据；每行显式提供有序检索计划。~ 表示同类备选。
const groups = [
  ['rice', '米饭／盖饭', [
    ['roast-rice', '烤肉拌饭', '烤肉拌饭', '~拌饭'],
    ['braised-chicken', '黄焖鸡米饭', '黄焖鸡米饭', '黄焖鸡'],
    ['braised-pork-rice', '卤肉饭', '卤肉饭', '卤肉盖饭'],
    ['pork-feet-rice', '猪脚饭', '猪脚饭', '隆江猪脚饭'],
    ['claypot-rice', '煲仔饭', '煲仔饭'],
    ['curry-chicken', '咖喱鸡饭', '咖喱鸡饭', '~咖喱饭'],
    ['pepper-beef', '黑椒牛柳饭', '黑椒牛柳', '~盖浇饭'],
    ['ribs-rice', '排骨饭', '排骨饭', '~排骨'],
  ]],
  ['noodles', '面', [
    ['lanzhou-beef', '兰州牛肉面', '兰州牛肉面', '兰州拉面', '~牛肉面'],
    ['chongqing-noodles', '重庆小面', '重庆小面', '小面', '~面馆'],
    ['knife-noodles', '刀削面', '刀削面', '~山西面馆'],
    ['zhajiang', '炸酱面', '炸酱面', '~面馆'],
    ['oil-noodles', '油泼面', '油泼面', '~陕西面馆'],
    ['hot-dry-noodles', '热干面', '热干面', '~武汉小吃'],
    ['pea-noodles', '豌杂面', '豌杂面', '豌杂小面', '~重庆小面'],
    ['scallion-noodles', '葱油拌面', '葱油拌面', '~上海面馆'],
  ]],
  ['rice-noodles', '粉／米线', [
    ['bridge-noodles', '过桥米线', '过桥米线', '~米线'],
    ['yunnan-pot', '云南小锅米线', '小锅米线', '~云南米线', '~米线'],
    ['guilin-noodles', '桂林米粉', '桂林米粉'],
    ['hunan-noodles', '湖南米粉', '湖南米粉', '~湖南粉馆'],
    ['jiangxi-noodles', '江西米粉', '江西米粉', '~南昌拌粉'],
    ['snail-noodles', '螺蛳粉', '螺蛳粉'],
    ['sour-noodles', '酸辣粉', '酸辣粉'],
    ['beef-rice-noodles', '牛肉粉', '牛肉粉', '~米粉'],
  ]],
  ['stir-fry', '小炒配饭', [
    ['chili-pork', '辣椒炒肉配米饭', '辣椒炒肉', '~湘菜', '~小炒'],
    ['fish-flavor-pork', '鱼香肉丝配米饭', '鱼香肉丝', '~川菜', '~家常菜'],
    ['kung-pao', '宫保鸡丁配米饭', '宫保鸡丁', '~家常菜', '~小炒'],
    ['twice-cooked-pork', '回锅肉配米饭', '回锅肉', '~川菜', '~家常菜'],
    ['tomato-egg', '番茄炒蛋配米饭', '番茄炒蛋', '~家常菜', '~小炒'],
    ['mushu-pork', '木须肉配米饭', '木须肉', '~家常菜', '~小炒'],
    ['potato-beef', '土豆牛肉配米饭', '土豆牛肉', '~家常菜', '~小炒'],
    ['mapo-tofu', '麻婆豆腐配米饭', '麻婆豆腐', '~川菜', '~家常菜'],
  ]],
  ['pots', '一锅／砂锅', [
    ['malatang', '麻辣烫', '麻辣烫'],
    ['maocai', '冒菜', '冒菜'],
    ['spicy-pot', '麻辣香锅', '麻辣香锅', '香锅'],
    ['chicken-pot', '鸡公煲', '鸡公煲'],
    ['sour-fish', '酸菜鱼', '酸菜鱼'],
    ['boiled-pork', '水煮肉片配米饭', '水煮肉片', '~川菜'],
    ['dry-chicken', '干锅鸡', '干锅鸡', '~干锅'],
    ['claypot-tofu', '砂锅豆腐配米饭', '砂锅豆腐', '~砂锅', '~家常菜'],
  ]],
  ['dumplings', '饺子／小吃主食', [
    ['dumplings', '水饺', '水饺', '饺子'],
    ['potstickers', '锅贴', '锅贴'],
    ['wonton', '馄饨', '馄饨'],
    ['red-wonton', '红油抄手', '红油抄手', '抄手', '~川味小吃'],
    ['pan-fried-buns', '生煎', '生煎', '生煎包'],
    ['roujiamo', '肉夹馍配凉皮', '肉夹馍', '凉皮', '~陕西小吃'],
    ['rice-rolls', '肠粉', '肠粉'],
    ['wonton-noodles', '云吞面', '云吞面', '~云吞'],
  ]],
  ['other', '其他日常', [
    ['roast-meat-rice', '烧腊饭', '烧腊饭', '~烧腊'],
    ['hainan-chicken', '海南鸡饭', '海南鸡饭'],
    ['bibimbap', '石锅拌饭', '石锅拌饭', '~韩式拌饭'],
    ['griddle-rice', '铁板饭', '铁板饭', '铁板炒饭'],
    ['chicken-cutlet', '鸡排饭', '鸡排饭', '~鸡排'],
    ['fried-chicken-rice', '炸鸡饭', '炸鸡饭', '~韩式炸鸡'],
    ['shaxian', '沙县拌面配蒸饺', '~沙县小吃', '~沙县'],
    ['burger-meal', '汉堡套餐', '汉堡'],
  ]],
  ['special', '特别', [
    ['sichuan-hotpot', '川渝火锅', '重庆火锅', '四川火锅', '~火锅'],
    ['chaoshan-hotpot', '潮汕牛肉火锅', '潮汕牛肉火锅', '牛肉火锅'],
    ['korean-bbq', '韩式烤肉', '韩式烤肉', '韩国烤肉', '~烤肉'],
    ['charcoal-bbq', '炭火烧烤', '炭火烧烤', '~烧烤'],
    ['sushi', '日式寿司', '寿司'],
    ['izakaya', '日式居酒屋', '居酒屋'],
    ['buffet', '自助餐', '自助餐'],
    ['grilled-fish', '烤鱼', '烤鱼'],
  ]],
];
export const FOODS = Object.freeze(groups.flatMap(([group, category, rows]) => rows.map(([id, name, ...queries]) => Object.freeze({
  id, name, category, pool: group === 'special' ? 'special' : 'everyday',
  searchPlan: Object.freeze(queries.map(q => Object.freeze({ keyword: q.replace(/^~/, ''), matchLevel: q.startsWith('~') ? 'related' : 'specific' }))),
}))));
export const EVERYDAY = Object.freeze(FOODS.filter(f => f.pool === 'everyday'));
export const SPECIAL = Object.freeze(FOODS.filter(f => f.pool === 'special'));
export const FOOD_BY_ID = new Map(FOODS.map(f => [f.id, f]));
